### ISSUE TITLE
Allow for a banned file list.

### ISSUE THREAD

**Issue by Luminarys** [Guad/fuwa#17]
Prevent files whose random name/hash are present in some banned file list from being saved.

**Comment by Guad** [comment]
Would a simple .csv file be good for a banlist? What would the fields be? The hash, and the reason it's blacklisted?

**Comment by Luminarys** [comment]
Sure that would probably be fine, though the reason might not be necessary(though useful for future reference).

**Comment by Guad** [comment]
Implemented in 4eae405f11dee50a10cd05fdc44b8a370d885912
