### ISSUE TITLE
Do proper name collision checking

### ISSUE THREAD

**Issue by Luminarys** [Guad/fuwa#28]
With only 6 \* 10^7 possible file names(36^5), the chance of collision will become incredibly high if a substantial amount of files are uploaded. Based on https://en.wikipedia.org/wiki/Birthday_attack, it would most likely take around 5k uploads before a 25% collision chance is reached, which is a fairly small amount. The problem is that because there is no DB or record storer of file hashes, the current method of seeding a Python random number generator is the only way to prevent duplicates. This means there are only two real options available - either significantly increase the namespace for file names, or switch to utilizing a DB to store information. I'm going to recommend the latter as it can also make system administration much easier down the line, as well as being fairly convenient.

**Comment by Guad** [comment]
So if I understand right, you're suggesting it to work like this:
![Flowchart](https://fuwa.se/02rcx.png)

P.S. I was quite sick these days so I couldn't answer before.

**Comment by Luminarys** [comment]
A process like that should work fine. The file names could also be increased to 6 chars rather than the current 5 to further decrease the collision chances. I'll leave it up to you as to how the DB should be structured, but I recommend you have columns for the original file name, new file name, md5 hash, and date/time the file was added.
