### ISSUE TITLE
Utilize a DB in the backend

### ISSUE THREAD

**Issue by Luminarys** [Guad/fuwa#29]
As I touched upon in the previous issue, a database should probably be used. For portability and ease of use(no setup or daemon needed), SQLite can be used. For higher throughput, MySQL or PostGreSQL are decent alternatives. The DB should probably store basic info about files in one table such as date/time uploaded, hash, new name, etc. as well as have a table for banned files.

**Comment by Luminarys** [comment]
Could you give me the schema of the db, or implement a function which automatically created a sqlite db with the proper schema initially in some sort of setup.py? The latter would probably be preferred as it would be easier for people to just clone, run some setup script and then start the server, but either should work.

**Comment by Guad** [comment]
Just run app.py once and it should create one in the root directory.

2015-07-14 0:11 GMT+02:00 Ezra notifications@github.com:
